### ISSUE TITLE
How to download the full database

### ISSUE THREAD

**Issue by zji90** [TIBHannover/BacDiveR#114]
Hi,

I wonder whether there is a way to download the full BacDive database without doing the search? Thanks!

**Comment by katrinleinweber** [comment]
Hi @zji90 👋 It's probably best to [contact the official BacDive team](https://bacdive.dsmz.de/contact) about that.

From my outside observation (now almost 2 years ago), I think there are 2 options in which BacDiveR can help you unofficially:

1. Iterating up from [bd_retrieve](https://tibhannover.github.io/BacDiveR/reference/bd_retrieve.html)(id = 1) to ([currently](https://bacdive.dsmz.de/advsearch) 82892), with a reasonable wait time in between (half a second?) and some client-side catching/skipping of errors (some IDs were nonexistent).
1. [Mass-downloading datasets](https://tibhannover.github.io/BacDiveR/articles/pre-configuring-advanced-searches-and-retrieving-the-results.html#mass-downloading-datasets) with a few very general search queries, like `Domain contains Bacteria` and  `Domain contains Archaea`.

**Comment by JackLMc** [comment]
For others that found this... This is the reply I received from the BacDive team:

"BacDive is a complex database with over 1000 data fields. Therefore there is no easy way to download the whole database (e.g. as a plain spreadsheet).
We recommend using the API for accessing data for many strains at once. Please have a look. Access is free after registration and we do provide clients for Python and R.

If you a further questions don't hesitate to ask.

Best regards,"

**Comment by katrinleinweber** [comment]
I wonder why they never contributed to this client, despite seeking cooperation projects with TIB. Case closed then, also because of #118.
