### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by CipherTwo** [TIBHannover/BacDiveR#119]
I try to install BacDiveR, but it hangs with "testing if installed package can be loaded from temporary location".
And my working environment:
`R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6`

**Comment by katrinleinweber** [comment]
Hi @CipherTwo 👋  That seems to be a duplicate of https://github.com/TIBHannover/BacDiveR/issues/115. Could you please try my advice there, and re-open it, if the problem persists?

**Comment by CipherTwo** [comment]
Thank you! I haven't seen that one.
