### ISSUE TITLE
Error: lexical error: invalid character inside string

### ISSUE THREAD

**Issue by jotech** [TIBHannover/BacDiveR#91]
Hi,
thank you for providing this useful package :)

Besides most queries working quite well, I'm having problems to get data for a specific bacdive id:
```R
retrieve_data(searchTerm=76, searchType = "bacdive_id")
76 Error: lexical error: invalid character inside string.
          r with 200 mg cycloheximide ml 21", "enrichment_cult_composi
                     (right here) ------^
```
The corresponding entry is:
 https://bacdive.dsmz.de/search?search=76

I'm not sure what causes the error maybe a linebreak?

**Comment by katrinleinweber** [comment]
Yeah, something like this. I already implemented https://github.com/TIBHannover/BacDiveR/commit/b9db8be05e95ffd37d7380edd366ad7a173186f9 & https://github.com/TIBHannover/BacDiveR/blob/18cb3d70229f0bbd7d09906035dadcc9ba686b4e/R/util-repair_escaping.R#L12-L17

to catch those, but it seems there is another one. Thanks for posting the exact entry. I'll start digging into this.

**Comment by katrinleinweber** [comment]
Ah, I implemented that repair only during aggregation of multiple datasets, not for an individual. Fix incoming 🎉

**Comment by jotech** [comment]
this worked, great thank you :)

**Comment by JackLMc** [comment]
This seems to have cropped back up as an issue in ```bd_retrieve(id = "717") ```
In fact, when testing all the examples, I am getting the same lexical error.

**Comment by katrinleinweber** [comment]
Hi @JackLMc 👋 Please see #118 for the reason. Thanks for trying BacDiveR, nonetheless :-)
