### ISSUE TITLE
retrieve_data: argument is of length zero

### ISSUE THREAD

**Issue by jotech** [TIBHannover/BacDiveR#92]
Hi,
after updating to the newest version, i'm getting some strange error:
```R
retrieve_data(searchTerm=43, searchType = "bacdive_id")
43 Error in if (payload$detail == "Not found") { : 
  argument is of length zero
```
This worked before using version 18cb3d70229f0bbd7d09906035dadcc9ba686b4e
Thanks for having a look

**Comment by katrinleinweber** [comment]
You're welcome and 1k thanks again for reporting this bug :-)

I think I'll let it run through their entire DB now to find more error-causing datasets.
